---
title: "Create Ensembl Transcript Annotation File"
output: html_document
---

Useful resources:
http://bioconductor.org/packages/release/bioc/html/ensembldb.html
http://bioconductor.org/packages/release/data/annotation/html/EnsDb.Hsapiens.v86.html
https://bioconductor.org/packages/devel/bioc/vignettes/tximport/inst/doc/tximport.html

browseVignettes("ensembldb")


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
BiocManager::install("ensembldb")
BiocManager::install("EnsDb.Hsapiens.v86")
BiocManager::install("tximportData")
BiocManager::install("tximport")
```

# Import required libraries
```{r libs}
library(ensembldb)
library(EnsDb.Hsapiens.v86)
```

# load ensemble db
```{r ensdb, echo=FALSE}
edb = EnsDb.Hsapiens.v86
```

Create db as DataFrame
```{r tx}
tx = transcripts(edb, return.type="DataFrame")
head(tx)
```

Create conversion table. Order of columns is important.
```{r}
tx2gene = as.data.frame(tx[, c('tx_name', 'gene_id')])
head(tx2gene)
```

```{r}
samples = c('WB-1044190', 'WB-1044191', 'WB-1044192')
files = file.path('/Users/mdascenzo/workspace/dev_analysis/rnaseq_pipeline/salmon', samples, 'quant.sf')
names(files) = samples 
all(file.exists(files))
```

```{r}
library(tximport)
txi <- tximport(files, type = "salmon", tx2gene = tx2gene)
names(txi)
```


```{r}
head(txi$counts)
```

Save tx2gene as a csv file for future use
```{r}
library(readr)
write_csv(tx2gene, 'tx2gene.EnsDb.Hsapiens.v86.csv' )
```

Load from file
```{r}
library(readr)
tx2gene = read_csv('tx2gene.EnsDb.Hsapiens.v86.csv')
head(tx2gene)
```


```{r}
library(tximport)
txi.salmon <- tximport(files, type = "salmon", tx2gene = tx2gene)
names(txi)
```

```{r}
head(txi.salmon$counts)
```

Prep for DESeq2
```{r}
library(DESeq2)

# define sample conditions
sampleTable = data.frame(condition =factor(c('N', 'N', 'D')), assay=factor(c('1', '2', '1')))
dds <- DESeqDataSetFromTximport(txi, sampleTable, ~condition + assay)

head(dds)       
```










