version: "3.7"
services:
  env:
    build: env
    image:.amazonaws.com/pcluster_admin
    container_name: pcluster_admin
    volumes:
    - type: bind
      source: ~/.aws
      target: /root/.aws
      bind:
        create_host_path: false
    - type: bind
      source: ~/.ssh
      target: /root/.ssh
      bind:
        create_host_path: false
    - type: bind
      source: ~/.parallelcluster 
      target: /root/.parallelcluster 
      bind:
        create_host_path: false
    - type: bind
      source: ../../workflows 
      target: /code/workflows 
      bind:
        create_host_path: false