jobs: 100
cluster: "sbatch -p {params.partition} --job-name {rule}_{wildcards} -t {resources.time_min} -c {resources.ncpu} -o logs/{rule}_{wildcards} -e logs/{rule}_{wildcards}"
default-resources: [ncpu=1, time_min=0]